### ISSUE TITLE
Failed to Deploy

### ISSUE THREAD

**Issue by sardarms** [sveltia/sveltia-cms-auth#7]
While trying to deply, I am getting this error:

> deploy
> Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

It has issues with "Enable GitHub Actions".

Sorry, I don't have the required technical skills to understand or address the issue.

**Comment by nioc** [comment]
Hello, same issue for me

**Comment by kyoshino** [comment]
Hey folks, the issue has been solved in https://github.com/sveltia/sveltia-cms-auth/pull/6. I have confirmed that the deployment is now [working](https://github.com/kyoshino/sveltia-cms-auth/actions/runs/7514126758). Please click the Deploy button and try again.

**Comment by nioc** [comment]
As usual, thanks @kyoshino 👍

**Comment by kyoshino** [comment]
Ah, the credit goes to @srtee 😃
