### ISSUE TITLE
The redirect URI included is not valid

### ISSUE THREAD

**Issue by kernitus** [sveltia/sveltia-cms-auth#8]
Setting this up with GitLab with the redirect URL given in the readme results in the error message `The redirect URI included is not valid.` However, configuring the gitlab oauth app callback url to be `<YOUR_WORKER_URL>/callback` instead of `<YOUR_WORKER_URL>/oauth/redirect` makes it work, i.e. the value given for GitHub, not GitLab.

Is this a bug has the readme just not been updated?

**Comment by kyoshino** [comment]
@kernitus Thanks for the heads-up! Yeah, the documentation seems wrong. The Redirect URI has to be `<YOUR_WORKER_URL>/callback` for both GitHub and GitLab. Will update the doc shortly.
